united-build: 
language: generic
sudo: required
services:
- docker
# DISABLE before_install if you want build with mock
before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull davidva/unibuild
script:
# ENABLE tne next line and delete add a "#" the next lines; if you want build with mock
#- travis_wait 40 docker run --cap-add=SYS_ADMIN davidva/unibuild /bin/sh /urpms -g UnitedRPMs/spotify -s spotify.spec -t fedora-25-x86_64
- docker run -v $(pwd):/root/enjoy --cap-add=SYS_ADMIN davidva/unibuild-27 /bin/sh -c "rm -f urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/broadcom-wl-dkms -s broadcom-wl-dkms.spec -r true -d 'dist .fc27' -u true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bbc656ea277114ba4fd
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
